---
#
# roles/common/tasks/main.yml
#

- name: stop unnecessary service
  service: name="{{ item }}" state=stopped enabled=no
  with_items:
  - NetworkManager
  - iptables
  - ip6tables
  ignore_errors: true


- name: install packages from base
  zypper: name="{{ item }}" state=latest
  with_items:
  - vim
  - wget
  - openssl
  - openssl-devel
  - tree
  - telnet
  - nkf
  - mlocate
  - expect
  - ntp
  - dstat
  - htop
  - iftop
  - git

- name: change localtime to JST
  file: >
    src=/usr/share/zoneinfo/Asia/Tokyo
    dest=/etc/localtime
    force=yes
    state=link
